# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yanan/CLionProjects/untitled1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yanan/CLionProjects/untitled1/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yanan/CLionProjects/untitled1/cmake-build-debug/CMakeFiles /Users/yanan/CLionProjects/untitled1/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yanan/CLionProjects/untitled1/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named n

# Build rule for target.
n : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 n
.PHONY : n

# fast build rule for target.
n/fast:
	$(MAKE) -f CMakeFiles/n.dir/build.make CMakeFiles/n.dir/build
.PHONY : n/fast

#=============================================================================
# Target rules for targets named q

# Build rule for target.
q : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 q
.PHONY : q

# fast build rule for target.
q/fast:
	$(MAKE) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/build
.PHONY : q/fast

#=============================================================================
# Target rules for targets named t

# Build rule for target.
t : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 t
.PHONY : t

# fast build rule for target.
t/fast:
	$(MAKE) -f CMakeFiles/t.dir/build.make CMakeFiles/t.dir/build
.PHONY : t/fast

#=============================================================================
# Target rules for targets named r

# Build rule for target.
r : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 r
.PHONY : r

# fast build rule for target.
r/fast:
	$(MAKE) -f CMakeFiles/r.dir/build.make CMakeFiles/r.dir/build
.PHONY : r/fast

#=============================================================================
# Target rules for targets named p

# Build rule for target.
p : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p
.PHONY : p

# fast build rule for target.
p/fast:
	$(MAKE) -f CMakeFiles/p.dir/build.make CMakeFiles/p.dir/build
.PHONY : p/fast

#=============================================================================
# Target rules for targets named l

# Build rule for target.
l : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 l
.PHONY : l

# fast build rule for target.
l/fast:
	$(MAKE) -f CMakeFiles/l.dir/build.make CMakeFiles/l.dir/build
.PHONY : l/fast

#=============================================================================
# Target rules for targets named k

# Build rule for target.
k : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 k
.PHONY : k

# fast build rule for target.
k/fast:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/build
.PHONY : k/fast

#=============================================================================
# Target rules for targets named j

# Build rule for target.
j : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 j
.PHONY : j

# fast build rule for target.
j/fast:
	$(MAKE) -f CMakeFiles/j.dir/build.make CMakeFiles/j.dir/build
.PHONY : j/fast

#=============================================================================
# Target rules for targets named i

# Build rule for target.
i : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 i
.PHONY : i

# fast build rule for target.
i/fast:
	$(MAKE) -f CMakeFiles/i.dir/build.make CMakeFiles/i.dir/build
.PHONY : i/fast

#=============================================================================
# Target rules for targets named o

# Build rule for target.
o : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 o
.PHONY : o

# fast build rule for target.
o/fast:
	$(MAKE) -f CMakeFiles/o.dir/build.make CMakeFiles/o.dir/build
.PHONY : o/fast

#=============================================================================
# Target rules for targets named h

# Build rule for target.
h : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 h
.PHONY : h

# fast build rule for target.
h/fast:
	$(MAKE) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/build
.PHONY : h/fast

#=============================================================================
# Target rules for targets named m

# Build rule for target.
m : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 m
.PHONY : m

# fast build rule for target.
m/fast:
	$(MAKE) -f CMakeFiles/m.dir/build.make CMakeFiles/m.dir/build
.PHONY : m/fast

#=============================================================================
# Target rules for targets named g

# Build rule for target.
g : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 g
.PHONY : g

# fast build rule for target.
g/fast:
	$(MAKE) -f CMakeFiles/g.dir/build.make CMakeFiles/g.dir/build
.PHONY : g/fast

#=============================================================================
# Target rules for targets named s

# Build rule for target.
s : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 s
.PHONY : s

# fast build rule for target.
s/fast:
	$(MAKE) -f CMakeFiles/s.dir/build.make CMakeFiles/s.dir/build
.PHONY : s/fast

#=============================================================================
# Target rules for targets named f

# Build rule for target.
f : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 f
.PHONY : f

# fast build rule for target.
f/fast:
	$(MAKE) -f CMakeFiles/f.dir/build.make CMakeFiles/f.dir/build
.PHONY : f/fast

#=============================================================================
# Target rules for targets named 3

# Build rule for target.
3 : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 3
.PHONY : 3

# fast build rule for target.
3/fast:
	$(MAKE) -f CMakeFiles/3.dir/build.make CMakeFiles/3.dir/build
.PHONY : 3/fast

#=============================================================================
# Target rules for targets named e

# Build rule for target.
e : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 e
.PHONY : e

# fast build rule for target.
e/fast:
	$(MAKE) -f CMakeFiles/e.dir/build.make CMakeFiles/e.dir/build
.PHONY : e/fast

#=============================================================================
# Target rules for targets named c

# Build rule for target.
c : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 c
.PHONY : c

# fast build rule for target.
c/fast:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/build
.PHONY : c/fast

#=============================================================================
# Target rules for targets named b

# Build rule for target.
b : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 b
.PHONY : b

# fast build rule for target.
b/fast:
	$(MAKE) -f CMakeFiles/b.dir/build.make CMakeFiles/b.dir/build
.PHONY : b/fast

#=============================================================================
# Target rules for targets named 2

# Build rule for target.
2 : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 2
.PHONY : 2

# fast build rule for target.
2/fast:
	$(MAKE) -f CMakeFiles/2.dir/build.make CMakeFiles/2.dir/build
.PHONY : 2/fast

#=============================================================================
# Target rules for targets named 1

# Build rule for target.
1 : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 1
.PHONY : 1

# fast build rule for target.
1/fast:
	$(MAKE) -f CMakeFiles/1.dir/build.make CMakeFiles/1.dir/build
.PHONY : 1/fast

#=============================================================================
# Target rules for targets named a

# Build rule for target.
a : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 a
.PHONY : a

# fast build rule for target.
a/fast:
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/build
.PHONY : a/fast

#=============================================================================
# Target rules for targets named untitled1

# Build rule for target.
untitled1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 untitled1
.PHONY : untitled1

# fast build rule for target.
untitled1/fast:
	$(MAKE) -f CMakeFiles/untitled1.dir/build.make CMakeFiles/untitled1.dir/build
.PHONY : untitled1/fast

1-13-.o: 1-13-.cpp.o

.PHONY : 1-13-.o

# target to build an object file
1-13-.cpp.o:
	$(MAKE) -f CMakeFiles/1.dir/build.make CMakeFiles/1.dir/1-13-.cpp.o
.PHONY : 1-13-.cpp.o

1-13-.i: 1-13-.cpp.i

.PHONY : 1-13-.i

# target to preprocess a source file
1-13-.cpp.i:
	$(MAKE) -f CMakeFiles/1.dir/build.make CMakeFiles/1.dir/1-13-.cpp.i
.PHONY : 1-13-.cpp.i

1-13-.s: 1-13-.cpp.s

.PHONY : 1-13-.s

# target to generate assembly for a file
1-13-.cpp.s:
	$(MAKE) -f CMakeFiles/1.dir/build.make CMakeFiles/1.dir/1-13-.cpp.s
.PHONY : 1-13-.cpp.s

1-13.o: 1-13.c.o

.PHONY : 1-13.o

# target to build an object file
1-13.c.o:
	$(MAKE) -f CMakeFiles/2.dir/build.make CMakeFiles/2.dir/1-13.c.o
.PHONY : 1-13.c.o

1-13.i: 1-13.c.i

.PHONY : 1-13.i

# target to preprocess a source file
1-13.c.i:
	$(MAKE) -f CMakeFiles/2.dir/build.make CMakeFiles/2.dir/1-13.c.i
.PHONY : 1-13.c.i

1-13.s: 1-13.c.s

.PHONY : 1-13.s

# target to generate assembly for a file
1-13.c.s:
	$(MAKE) -f CMakeFiles/2.dir/build.make CMakeFiles/2.dir/1-13.c.s
.PHONY : 1-13.c.s

1-14.o: 1-14.c.o

.PHONY : 1-14.o

# target to build an object file
1-14.c.o:
	$(MAKE) -f CMakeFiles/3.dir/build.make CMakeFiles/3.dir/1-14.c.o
.PHONY : 1-14.c.o

1-14.i: 1-14.c.i

.PHONY : 1-14.i

# target to preprocess a source file
1-14.c.i:
	$(MAKE) -f CMakeFiles/3.dir/build.make CMakeFiles/3.dir/1-14.c.i
.PHONY : 1-14.c.i

1-14.s: 1-14.c.s

.PHONY : 1-14.s

# target to generate assembly for a file
1-14.c.s:
	$(MAKE) -f CMakeFiles/3.dir/build.make CMakeFiles/3.dir/1-14.c.s
.PHONY : 1-14.c.s

3-2.o: 3-2.cpp.o

.PHONY : 3-2.o

# target to build an object file
3-2.cpp.o:
	$(MAKE) -f CMakeFiles/j.dir/build.make CMakeFiles/j.dir/3-2.cpp.o
.PHONY : 3-2.cpp.o

3-2.i: 3-2.cpp.i

.PHONY : 3-2.i

# target to preprocess a source file
3-2.cpp.i:
	$(MAKE) -f CMakeFiles/j.dir/build.make CMakeFiles/j.dir/3-2.cpp.i
.PHONY : 3-2.cpp.i

3-2.s: 3-2.cpp.s

.PHONY : 3-2.s

# target to generate assembly for a file
3-2.cpp.s:
	$(MAKE) -f CMakeFiles/j.dir/build.make CMakeFiles/j.dir/3-2.cpp.s
.PHONY : 3-2.cpp.s

3-3.o: 3-3.cpp.o

.PHONY : 3-3.o

# target to build an object file
3-3.cpp.o:
	$(MAKE) -f CMakeFiles/o.dir/build.make CMakeFiles/o.dir/3-3.cpp.o
.PHONY : 3-3.cpp.o

3-3.i: 3-3.cpp.i

.PHONY : 3-3.i

# target to preprocess a source file
3-3.cpp.i:
	$(MAKE) -f CMakeFiles/o.dir/build.make CMakeFiles/o.dir/3-3.cpp.i
.PHONY : 3-3.cpp.i

3-3.s: 3-3.cpp.s

.PHONY : 3-3.s

# target to generate assembly for a file
3-3.cpp.s:
	$(MAKE) -f CMakeFiles/o.dir/build.make CMakeFiles/o.dir/3-3.cpp.s
.PHONY : 3-3.cpp.s

3-4-1.o: 3-4-1.cpp.o

.PHONY : 3-4-1.o

# target to build an object file
3-4-1.cpp.o:
	$(MAKE) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/3-4-1.cpp.o
.PHONY : 3-4-1.cpp.o

3-4-1.i: 3-4-1.cpp.i

.PHONY : 3-4-1.i

# target to preprocess a source file
3-4-1.cpp.i:
	$(MAKE) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/3-4-1.cpp.i
.PHONY : 3-4-1.cpp.i

3-4-1.s: 3-4-1.cpp.s

.PHONY : 3-4-1.s

# target to generate assembly for a file
3-4-1.cpp.s:
	$(MAKE) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/3-4-1.cpp.s
.PHONY : 3-4-1.cpp.s

3-4.o: 3-4.cpp.o

.PHONY : 3-4.o

# target to build an object file
3-4.cpp.o:
	$(MAKE) -f CMakeFiles/p.dir/build.make CMakeFiles/p.dir/3-4.cpp.o
.PHONY : 3-4.cpp.o

3-4.i: 3-4.cpp.i

.PHONY : 3-4.i

# target to preprocess a source file
3-4.cpp.i:
	$(MAKE) -f CMakeFiles/p.dir/build.make CMakeFiles/p.dir/3-4.cpp.i
.PHONY : 3-4.cpp.i

3-4.s: 3-4.cpp.s

.PHONY : 3-4.s

# target to generate assembly for a file
3-4.cpp.s:
	$(MAKE) -f CMakeFiles/p.dir/build.make CMakeFiles/p.dir/3-4.cpp.s
.PHONY : 3-4.cpp.s

3-5-1.o: 3-5-1.cpp.o

.PHONY : 3-5-1.o

# target to build an object file
3-5-1.cpp.o:
	$(MAKE) -f CMakeFiles/r.dir/build.make CMakeFiles/r.dir/3-5-1.cpp.o
.PHONY : 3-5-1.cpp.o

3-5-1.i: 3-5-1.cpp.i

.PHONY : 3-5-1.i

# target to preprocess a source file
3-5-1.cpp.i:
	$(MAKE) -f CMakeFiles/r.dir/build.make CMakeFiles/r.dir/3-5-1.cpp.i
.PHONY : 3-5-1.cpp.i

3-5-1.s: 3-5-1.cpp.s

.PHONY : 3-5-1.s

# target to generate assembly for a file
3-5-1.cpp.s:
	$(MAKE) -f CMakeFiles/r.dir/build.make CMakeFiles/r.dir/3-5-1.cpp.s
.PHONY : 3-5-1.cpp.s

3-5-2.o: 3-5-2.cpp.o

.PHONY : 3-5-2.o

# target to build an object file
3-5-2.cpp.o:
	$(MAKE) -f CMakeFiles/s.dir/build.make CMakeFiles/s.dir/3-5-2.cpp.o
.PHONY : 3-5-2.cpp.o

3-5-2.i: 3-5-2.cpp.i

.PHONY : 3-5-2.i

# target to preprocess a source file
3-5-2.cpp.i:
	$(MAKE) -f CMakeFiles/s.dir/build.make CMakeFiles/s.dir/3-5-2.cpp.i
.PHONY : 3-5-2.cpp.i

3-5-2.s: 3-5-2.cpp.s

.PHONY : 3-5-2.s

# target to generate assembly for a file
3-5-2.cpp.s:
	$(MAKE) -f CMakeFiles/s.dir/build.make CMakeFiles/s.dir/3-5-2.cpp.s
.PHONY : 3-5-2.cpp.s

6-4.o: 6-4.cpp.o

.PHONY : 6-4.o

# target to build an object file
6-4.cpp.o:
	$(MAKE) -f CMakeFiles/g.dir/build.make CMakeFiles/g.dir/6-4.cpp.o
.PHONY : 6-4.cpp.o

6-4.i: 6-4.cpp.i

.PHONY : 6-4.i

# target to preprocess a source file
6-4.cpp.i:
	$(MAKE) -f CMakeFiles/g.dir/build.make CMakeFiles/g.dir/6-4.cpp.i
.PHONY : 6-4.cpp.i

6-4.s: 6-4.cpp.s

.PHONY : 6-4.s

# target to generate assembly for a file
6-4.cpp.s:
	$(MAKE) -f CMakeFiles/g.dir/build.make CMakeFiles/g.dir/6-4.cpp.s
.PHONY : 6-4.cpp.s

6-5.o: 6-5.cpp.o

.PHONY : 6-5.o

# target to build an object file
6-5.cpp.o:
	$(MAKE) -f CMakeFiles/i.dir/build.make CMakeFiles/i.dir/6-5.cpp.o
.PHONY : 6-5.cpp.o

6-5.i: 6-5.cpp.i

.PHONY : 6-5.i

# target to preprocess a source file
6-5.cpp.i:
	$(MAKE) -f CMakeFiles/i.dir/build.make CMakeFiles/i.dir/6-5.cpp.i
.PHONY : 6-5.cpp.i

6-5.s: 6-5.cpp.s

.PHONY : 6-5.s

# target to generate assembly for a file
6-5.cpp.s:
	$(MAKE) -f CMakeFiles/i.dir/build.make CMakeFiles/i.dir/6-5.cpp.s
.PHONY : 6-5.cpp.s

6-6.o: 6-6.cpp.o

.PHONY : 6-6.o

# target to build an object file
6-6.cpp.o:
	$(MAKE) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/6-6.cpp.o
.PHONY : 6-6.cpp.o

6-6.i: 6-6.cpp.i

.PHONY : 6-6.i

# target to preprocess a source file
6-6.cpp.i:
	$(MAKE) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/6-6.cpp.i
.PHONY : 6-6.cpp.i

6-6.s: 6-6.cpp.s

.PHONY : 6-6.s

# target to generate assembly for a file
6-6.cpp.s:
	$(MAKE) -f CMakeFiles/h.dir/build.make CMakeFiles/h.dir/6-6.cpp.s
.PHONY : 6-6.cpp.s

86.o: 86.cpp.o

.PHONY : 86.o

# target to build an object file
86.cpp.o:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/86.cpp.o
.PHONY : 86.cpp.o

86.i: 86.cpp.i

.PHONY : 86.i

# target to preprocess a source file
86.cpp.i:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/86.cpp.i
.PHONY : 86.cpp.i

86.s: 86.cpp.s

.PHONY : 86.s

# target to generate assembly for a file
86.cpp.s:
	$(MAKE) -f CMakeFiles/k.dir/build.make CMakeFiles/k.dir/86.cpp.s
.PHONY : 86.cpp.s

d.o: d.c.o

.PHONY : d.o

# target to build an object file
d.c.o:
	$(MAKE) -f CMakeFiles/e.dir/build.make CMakeFiles/e.dir/d.c.o
.PHONY : d.c.o

d.i: d.c.i

.PHONY : d.i

# target to preprocess a source file
d.c.i:
	$(MAKE) -f CMakeFiles/e.dir/build.make CMakeFiles/e.dir/d.c.i
.PHONY : d.c.i

d.s: d.c.s

.PHONY : d.s

# target to generate assembly for a file
d.c.s:
	$(MAKE) -f CMakeFiles/e.dir/build.make CMakeFiles/e.dir/d.c.s
.PHONY : d.c.s

e3-2.o: e3-2.cpp.o

.PHONY : e3-2.o

# target to build an object file
e3-2.cpp.o:
	$(MAKE) -f CMakeFiles/n.dir/build.make CMakeFiles/n.dir/e3-2.cpp.o
.PHONY : e3-2.cpp.o

e3-2.i: e3-2.cpp.i

.PHONY : e3-2.i

# target to preprocess a source file
e3-2.cpp.i:
	$(MAKE) -f CMakeFiles/n.dir/build.make CMakeFiles/n.dir/e3-2.cpp.i
.PHONY : e3-2.cpp.i

e3-2.s: e3-2.cpp.s

.PHONY : e3-2.s

# target to generate assembly for a file
e3-2.cpp.s:
	$(MAKE) -f CMakeFiles/n.dir/build.make CMakeFiles/n.dir/e3-2.cpp.s
.PHONY : e3-2.cpp.s

exercise1-12.o: exercise1-12.c.o

.PHONY : exercise1-12.o

# target to build an object file
exercise1-12.c.o:
	$(MAKE) -f CMakeFiles/1.dir/build.make CMakeFiles/1.dir/exercise1-12.c.o
.PHONY : exercise1-12.c.o

exercise1-12.i: exercise1-12.c.i

.PHONY : exercise1-12.i

# target to preprocess a source file
exercise1-12.c.i:
	$(MAKE) -f CMakeFiles/1.dir/build.make CMakeFiles/1.dir/exercise1-12.c.i
.PHONY : exercise1-12.c.i

exercise1-12.s: exercise1-12.c.s

.PHONY : exercise1-12.s

# target to generate assembly for a file
exercise1-12.c.s:
	$(MAKE) -f CMakeFiles/1.dir/build.make CMakeFiles/1.dir/exercise1-12.c.s
.PHONY : exercise1-12.c.s

getline.o: getline.c.o

.PHONY : getline.o

# target to build an object file
getline.c.o:
	$(MAKE) -f CMakeFiles/untitled1.dir/build.make CMakeFiles/untitled1.dir/getline.c.o
.PHONY : getline.c.o

getline.i: getline.c.i

.PHONY : getline.i

# target to preprocess a source file
getline.c.i:
	$(MAKE) -f CMakeFiles/untitled1.dir/build.make CMakeFiles/untitled1.dir/getline.c.i
.PHONY : getline.c.i

getline.s: getline.c.s

.PHONY : getline.s

# target to generate assembly for a file
getline.c.s:
	$(MAKE) -f CMakeFiles/untitled1.dir/build.make CMakeFiles/untitled1.dir/getline.c.s
.PHONY : getline.c.s

getword.o: getword.c.o

.PHONY : getword.o

# target to build an object file
getword.c.o:
	$(MAKE) -f CMakeFiles/f.dir/build.make CMakeFiles/f.dir/getword.c.o
.PHONY : getword.c.o

getword.i: getword.c.i

.PHONY : getword.i

# target to preprocess a source file
getword.c.i:
	$(MAKE) -f CMakeFiles/f.dir/build.make CMakeFiles/f.dir/getword.c.i
.PHONY : getword.c.i

getword.s: getword.c.s

.PHONY : getword.s

# target to generate assembly for a file
getword.c.s:
	$(MAKE) -f CMakeFiles/f.dir/build.make CMakeFiles/f.dir/getword.c.s
.PHONY : getword.c.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/untitled1.dir/build.make CMakeFiles/untitled1.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/untitled1.dir/build.make CMakeFiles/untitled1.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/untitled1.dir/build.make CMakeFiles/untitled1.dir/main.cpp.s
.PHONY : main.cpp.s

p87.o: p87.cpp.o

.PHONY : p87.o

# target to build an object file
p87.cpp.o:
	$(MAKE) -f CMakeFiles/l.dir/build.make CMakeFiles/l.dir/p87.cpp.o
.PHONY : p87.cpp.o

p87.i: p87.cpp.i

.PHONY : p87.i

# target to preprocess a source file
p87.cpp.i:
	$(MAKE) -f CMakeFiles/l.dir/build.make CMakeFiles/l.dir/p87.cpp.i
.PHONY : p87.cpp.i

p87.s: p87.cpp.s

.PHONY : p87.s

# target to generate assembly for a file
p87.cpp.s:
	$(MAKE) -f CMakeFiles/l.dir/build.make CMakeFiles/l.dir/p87.cpp.s
.PHONY : p87.cpp.s

p94.o: p94.cpp.o

.PHONY : p94.o

# target to build an object file
p94.cpp.o:
	$(MAKE) -f CMakeFiles/t.dir/build.make CMakeFiles/t.dir/p94.cpp.o
.PHONY : p94.cpp.o

p94.i: p94.cpp.i

.PHONY : p94.i

# target to preprocess a source file
p94.cpp.i:
	$(MAKE) -f CMakeFiles/t.dir/build.make CMakeFiles/t.dir/p94.cpp.i
.PHONY : p94.cpp.i

p94.s: p94.cpp.s

.PHONY : p94.s

# target to generate assembly for a file
p94.cpp.s:
	$(MAKE) -f CMakeFiles/t.dir/build.make CMakeFiles/t.dir/p94.cpp.s
.PHONY : p94.cpp.s

struct.o: struct.c.o

.PHONY : struct.o

# target to build an object file
struct.c.o:
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/struct.c.o
.PHONY : struct.c.o

struct.i: struct.c.i

.PHONY : struct.i

# target to preprocess a source file
struct.c.i:
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/struct.c.i
.PHONY : struct.c.i

struct.s: struct.c.s

.PHONY : struct.s

# target to generate assembly for a file
struct.c.s:
	$(MAKE) -f CMakeFiles/a.dir/build.make CMakeFiles/a.dir/struct.c.s
.PHONY : struct.c.s

struct1.o: struct1.c.o

.PHONY : struct1.o

# target to build an object file
struct1.c.o:
	$(MAKE) -f CMakeFiles/b.dir/build.make CMakeFiles/b.dir/struct1.c.o
.PHONY : struct1.c.o

struct1.i: struct1.c.i

.PHONY : struct1.i

# target to preprocess a source file
struct1.c.i:
	$(MAKE) -f CMakeFiles/b.dir/build.make CMakeFiles/b.dir/struct1.c.i
.PHONY : struct1.c.i

struct1.s: struct1.c.s

.PHONY : struct1.s

# target to generate assembly for a file
struct1.c.s:
	$(MAKE) -f CMakeFiles/b.dir/build.make CMakeFiles/b.dir/struct1.c.s
.PHONY : struct1.c.s

struct2.o: struct2.c.o

.PHONY : struct2.o

# target to build an object file
struct2.c.o:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/struct2.c.o
.PHONY : struct2.c.o

struct2.i: struct2.c.i

.PHONY : struct2.i

# target to preprocess a source file
struct2.c.i:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/struct2.c.i
.PHONY : struct2.c.i

struct2.s: struct2.c.s

.PHONY : struct2.s

# target to generate assembly for a file
struct2.c.s:
	$(MAKE) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/struct2.c.s
.PHONY : struct2.c.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/m.dir/build.make CMakeFiles/m.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/m.dir/build.make CMakeFiles/m.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/m.dir/build.make CMakeFiles/m.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... n"
	@echo "... q"
	@echo "... t"
	@echo "... r"
	@echo "... p"
	@echo "... l"
	@echo "... k"
	@echo "... j"
	@echo "... i"
	@echo "... o"
	@echo "... h"
	@echo "... m"
	@echo "... g"
	@echo "... s"
	@echo "... f"
	@echo "... 3"
	@echo "... e"
	@echo "... c"
	@echo "... b"
	@echo "... 2"
	@echo "... 1"
	@echo "... a"
	@echo "... untitled1"
	@echo "... 1-13-.o"
	@echo "... 1-13-.i"
	@echo "... 1-13-.s"
	@echo "... 1-13.o"
	@echo "... 1-13.i"
	@echo "... 1-13.s"
	@echo "... 1-14.o"
	@echo "... 1-14.i"
	@echo "... 1-14.s"
	@echo "... 3-2.o"
	@echo "... 3-2.i"
	@echo "... 3-2.s"
	@echo "... 3-3.o"
	@echo "... 3-3.i"
	@echo "... 3-3.s"
	@echo "... 3-4-1.o"
	@echo "... 3-4-1.i"
	@echo "... 3-4-1.s"
	@echo "... 3-4.o"
	@echo "... 3-4.i"
	@echo "... 3-4.s"
	@echo "... 3-5-1.o"
	@echo "... 3-5-1.i"
	@echo "... 3-5-1.s"
	@echo "... 3-5-2.o"
	@echo "... 3-5-2.i"
	@echo "... 3-5-2.s"
	@echo "... 6-4.o"
	@echo "... 6-4.i"
	@echo "... 6-4.s"
	@echo "... 6-5.o"
	@echo "... 6-5.i"
	@echo "... 6-5.s"
	@echo "... 6-6.o"
	@echo "... 6-6.i"
	@echo "... 6-6.s"
	@echo "... 86.o"
	@echo "... 86.i"
	@echo "... 86.s"
	@echo "... d.o"
	@echo "... d.i"
	@echo "... d.s"
	@echo "... e3-2.o"
	@echo "... e3-2.i"
	@echo "... e3-2.s"
	@echo "... exercise1-12.o"
	@echo "... exercise1-12.i"
	@echo "... exercise1-12.s"
	@echo "... getline.o"
	@echo "... getline.i"
	@echo "... getline.s"
	@echo "... getword.o"
	@echo "... getword.i"
	@echo "... getword.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... p87.o"
	@echo "... p87.i"
	@echo "... p87.s"
	@echo "... p94.o"
	@echo "... p94.i"
	@echo "... p94.s"
	@echo "... struct.o"
	@echo "... struct.i"
	@echo "... struct.s"
	@echo "... struct1.o"
	@echo "... struct1.i"
	@echo "... struct1.s"
	@echo "... struct2.o"
	@echo "... struct2.i"
	@echo "... struct2.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

